# Generated by Django 6.0.7 on 2026-07-14 07:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('BUILD_MUSCLE', 'Build muscle'), ('LOSE_WEIGHT', 'Lose weight'), ('STAY_FIT', 'Stay fit')], default='BUILD_MUSCLE', max_length=20)),
                ('days_per_week', models.PositiveSmallIntegerField(default=3, help_text='Planned training days per week (1-7).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('experience_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
                ('workout_location', models.CharField(choices=[('COMMERCIAL_GYM', 'Commercial gym'), ('HOME', 'Home'), ('LIMITED_EQUIPMENT', 'Limited equipment')], default='COMMERCIAL_GYM', max_length=20)),
                ('session_duration', models.PositiveSmallIntegerField(default=60, help_text='Typical session length in minutes.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(240)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
