# Generated by Django 6.0.7 on 2026-07-15 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(help_text='Your age in years.', null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(help_text='Your height in centimetres.', null=True, validators=[django.core.validators.MinValueValidator(90), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.DecimalField(decimal_places=1, help_text='Your body weight in kilograms.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(400)]),
        ),
    ]
