# Generated by Django 6.0.7 on 2026-07-15 08:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_age_userprofile_height_cm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=1, help_text='Body weight in kilograms.', max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(400)])),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=1, help_text='Body fat percentage, if your scale reports it.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(70)])),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=1, help_text='Muscle mass in kilograms, if your scale reports it.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(150)])),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_on'],
                'indexes': [models.Index(fields=['user', '-recorded_on'], name='users_bodym_user_id_97a7ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'recorded_on'), name='one_measurement_per_user_per_day')],
            },
        ),
    ]
