# Generated by Django 6.0.7 on 2026-07-15 11:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bodymeasurement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('activity_level', models.CharField(choices=[('SEDENTARY', 'Sedentary: little or no exercise'), ('LIGHT', 'Light: exercise 1–3 times/week'), ('MODERATE', 'Moderate: exercise 4–5 times/week'), ('ACTIVE', 'Active: daily exercise or intense exercise 3–4 times/week'), ('VERY_ACTIVE', 'Very active: intense exercise 6–7 times/week'), ('EXTRA_ACTIVE', 'Extra active: very intense exercise daily, or a physical job')], max_length=20)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(80)])),
                ('height_cm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(90), django.core.validators.MaxValueValidator(250)])),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(400)])),
                ('bmr', models.PositiveIntegerField()),
                ('maintenance_calories', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_calculation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
