# Generated by Django 6.0.7 on 2026-07-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_caloriecalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], help_text='Used for calorie estimates and to tailor your plan.', max_length=6, null=True),
        ),
    ]
