# Generated by Django 6.0.7 on 2026-07-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('TRAINEE', 'Trainee'), ('ADMIN', 'Admin')], default='TRAINEE', max_length=10),
        ),
    ]
