# Generated by Django 6.0.7 on 2026-07-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_shared',
            field=models.BooleanField(default=False),
        ),
    ]
