# Generated by Django 6.0.7 on 2026-07-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_bodymeasurement_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='When off, admins stop receiving new notifications.')),
                ('messaging_enabled', models.BooleanField(default=True, help_text='When off, trainees cannot message the admin.')),
                ('signups_enabled', models.BooleanField(default=True, help_text='When off, new trainees cannot register.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
