# Generated by Django 6.0.7 on 2026-07-14 07:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('muscle_group', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('SHOULDERS', 'Shoulders'), ('QUADRICEPS', 'Quadriceps'), ('HAMSTRINGS', 'Hamstrings'), ('GLUTES', 'Glutes'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('CALVES', 'Calves'), ('CORE', 'Core')], max_length=20)),
                ('equipment', models.CharField(choices=[('BARBELL', 'Barbell'), ('DUMBBELL', 'Dumbbell'), ('MACHINE', 'Machine'), ('CABLE', 'Cable'), ('BODYWEIGHT', 'Bodyweight'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Workout', max_length=100)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg. 0 is allowed for bodyweight exercises.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('reps', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('client_record_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutsession')),
            ],
            options={
                'ordering': ['exercise__name', 'set_number'],
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', '-started_at'], name='workouts_wo_user_id_76ea72_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'is_completed'], name='workouts_wo_user_id_10a6dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_completed', False)), fields=('user',), name='one_active_session_per_user'),
        ),
        migrations.AddIndex(
            model_name='workoutset',
            index=models.Index(fields=['session', 'exercise'], name='workouts_wo_session_07e9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutset',
            index=models.Index(fields=['exercise', 'created_at'], name='workouts_wo_exercis_1f09d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='weight_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.CheckConstraint(condition=models.Q(('reps__gte', 1)), name='reps_positive'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.CheckConstraint(condition=models.Q(('set_number__gte', 1)), name='set_number_positive'),
        ),
    ]
