# Generated by Django 6.0.7 on 2026-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
