# Generated by Django 6.0.7 on 2026-07-14 07:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('BUILD_MUSCLE', 'Build muscle'), ('LOSE_WEIGHT', 'Lose weight'), ('STAY_FIT', 'Stay fit')], max_length=20)),
                ('days_per_week', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('experience_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('workout_location', models.CharField(choices=[('COMMERCIAL_GYM', 'Commercial gym'), ('HOME', 'Home'), ('LIMITED_EQUIPMENT', 'Limited equipment')], max_length=20)),
                ('session_duration', models.PositiveSmallIntegerField()),
                ('plan_json', models.JSONField()),
                ('analytics_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_planner__user_id_541eb7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='one_active_plan_per_user')],
            },
        ),
    ]
