# Generated by Django 6.0.7 on 2026-07-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
