# Generated by Django 6.0.7 on 2026-07-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('MESSAGE', 'Message'), ('PROFILE', 'Profile update'), ('GOAL', 'Goal change'), ('CALORIES', 'Calorie update'), ('BODY', 'Body measurement'), ('WORKOUT', 'Workout'), ('NEW_TRAINEE', 'New trainee'), ('PERMISSION', 'Profile sharing'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
    ]
